apiVersion: apps/v1
kind: Deployment
metadata:
  name: me-random-status-app
  namespace: www-public
spec:
  replicas: 1
  selector:
    matchLabels:
      app: me-random-status-app
  template:
    metadata:
      labels:
        app: me-random-status-app
    spec:
      containers:
      - name: me-random-status-app
        image: aaraoz/random-status-app:1.0
        ports:
        - name: web
          containerPort: 80
        resources:
          requests:
            memory: 56Mi
            cpu: 100m
          limits:
            memory: 64Mi
            cpu: 250m
---
apiVersion: v1
kind: Service
metadata:
  name: me-random-status-app
  namespace: www-public
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: external-nginx
spec:
  type: NodePort
  selector:
    app: me-random-status-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: web
